spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/net_shop?createIfNotExists=true"
    username:
      someverynotprod_username
    password:
      someverynotprod_password
  jpa:
    hibernate:
      ddl-auto: validate
app:
  security:
    jwt:
      secret:
        someverynotprodsecret
      expiration:
        300000
server:
  servlet:
    context-path: /net-shop/api/